### ISSUE TITLE
Adjust adapter to support prooph/event-store 5.0

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-zf2-adapter#2]
See prooph/event-store#61

Depends on prooph/event-store#60

**Comment by codeliner** [comment]
A question came to my mind: Do we really need the ZF2 Tablegateway adapter?

We have the doctrine dbal adapter and now also the Mongo DB adapter. Two adapters which need to be maintained. The ZF2 Tablegateway version don't really add value. It is just a copy of the doctrine version (ok, doctrine version is a copy of the tablegateway, but the doctrine adapter is the preferred one by our users)

I'd like to abandon the adapter. What do you think @prolic ?

**Comment by prolic** [comment]
Absolutely right. We need to support databases, not database abstraction
frameworks.
Am 23.08.2015 10:39 schrieb "Alexander Miertsch" <notifications@github.com>:

**Comment by codeliner** [comment]
Great. I've added an info to the README and abandoned the package on packagist.
RIP Tablegateway adapter
